# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevinoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('result', jsonfield.fields.JSONField(blank=True, null=True)),
                ('is_fail', models.BooleanField(default=False)),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevinoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_resource', models.CharField(choices=[('send_text', 'send_text'), ('send_image', 'send_image'), ('send_text_and_button', 'send_text_and_button'), ('check_status_messages', 'check_status_messages')], max_length=64)),
                ('data', jsonfield.fields.JSONField(blank=True, null=True)),
                ('dc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='devinoanswer',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devino_answer', to='core.DevinoRequest'),
        ),
    ]
